name: ServerPolling
main: com.lazrcowboy.serverpolling.ServerPolling
version: 1.0.3
commands:
    poll:
        description: Opens the help menu
        usage: "Usage: /help to open the help menu"
permissions:
    serverpolling.commands.poll:
        description: "Allows access to the special help section (Should be given to everyone) ##NOT USED YET##"
    serverpolling.createpoll:
        description: "Allows access to create polls"